name: Web Scrape Exogenous variable data for certain key time-series features

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]
  schedule:
    - cron: "30 1 * * *"  # Schedule to run every day at 7:00 AM IST (adjust as needed)

jobs:
  execute_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.11  # Specify the Python version you need
          cache: 'pip'

#       - name: Install Jupyter
#         run: python -m pip install jupyter
        
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run script and update data
        run: |
          jupyter nbconvert --to script web_scraping.ipynb
          python web_scraping.py
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add exog_variables.csv 
          git add run_summary.json
          git commit -m "Updated data on `date` with GitHub Actions" || echo "No Changes to Commit"
          git push origin master || echo "No Changes to Commit"
